TEXTS = {
    "EN": {
        "BTN_GENERATE": "🎨 Generate Art",
        "BTN_EDIT": "🪄 Edit Photo",
        "BTN_HELP": "💡 Help",
        "BTN_PRO": "💎 High Detail (PRO)",
        "BTN_FLASH": "⚡️ High Speed (FLASH)",
        "BTN_LANG": "🌐 Language / Язык",
        "WELCOME": "Hello! 👋 I am a bot powered by Google Gemini models.\n\nPlease select an action on the keyboard below.",
        "CHOOSE_LANG": "Please select your language / Пожалуйста, выберите язык:",
        "LANG_SET": "Language set to English 🇬🇧",
        "GENERATE_PROMPT": "✨ <b>Generation Mode Activated</b>\n\nPlease send a detailed description (prompt) for the image you want to create. Both text and voice inputs are supported.",
        "EDIT_PROMPT": "📸 Please send the original <b>photo</b> to the chat. Afterwards, you can specify exactly what needs to be changed.",
        "HELP_TEXT": "💡 <b>Quick Guide:</b>\n\n• <b>Generate Art</b>: Create an image from scratch based on a description.\n• <b>Edit Photo</b>: Edit an existing photo using additional instructions.\n• <b>Quality Modes (PRO/FLASH)</b>: FLASH is perfect for quick sketches and text responses, while PRO handles high-quality detailing and complex instructions.",
        "PRO_ACTIVATED": "💎 PRO mode is activated (High detail and quality).",
        "FLASH_ACTIVATED": "⚡️ FLASH mode is activated (High speed and optimization).",
        "ERR_SAFETY": "⚠️ Error: The request was rejected by safety filters. Please try rephrasing your prompt.",
        "ERR_RATELIMIT": "⏳ Rate limit exceeded. We've sent too many commands. Please wait a minute.",
        "ERR_SERVER": "🔌 Google Gemini servers are temporarily unavailable. Please try again later.",
        "ERR_UNKNOWN": "⚙️ An unknown error occurred: {error}. Please try again.",
        "ERR_GEN_INTERNAL": "😔 An internal error occurred in the generation service. Please try again later.",
        "ERR_EDIT_INTERNAL": "😔 The editing service is unavailable. Please try your operation again later.",
        "ERR_AUDIO_TRANS": "⚠️ Could not transcribe the voice message. Please try writing your request in text.",
        "PROCESS_GEN_START": "🎨 Generation process has started, please wait...",
        "ERR_LOAD_EDIT": "⚠️ There was a problem loading your photo. Please select edit from the menu and try again.",
        "PROCESS_EDIT_PREP": "📥 Preparing your photo for processing...",
        "PROCESS_EDIT_GEN": "🪄 Generating edits... Please wait for the result.",
        "ERR_DL_TELEGRAM": "😢 Error downloading and processing the photo from Telegram. Please try again.",
        "ERR_NEED_PHOTO_NOT_TEXT": "Please send an actual <b>photo</b> (image) to proceed.",
        "ERR_MENU_FIRST": "Please select an action from the bot menu first (generate or edit).",
        "VOICE_NO_PHOTO": "This step requires a <b>photo</b> from you, not a voice message.",
        "PROCESS_VOICE_RX": "🎧 Receiving your audio message...",
        "PROCESS_VOICE_TRANS": "✍️ Transcribing voice to text...",
        "TXT_TRANSCRIBED": "🎙 <i>Transcribed text:</i> {text}",
        "ERR_VOICE_DL": "⚠️ Error: Failed to download the audio message. Please record and send it again.",
        "PHOTO_LOADED_PROMPT": "📸 Photo loaded. Please write or send a voice instruction on what needs to be changed in the picture.",
        "PHOTO_ALREADY_RX": "The photo has already been received! Now simply send a text or voice description of what needs to be changed.",
        "ERR_PHOTO_IN_GEN": "This mode only supports text requests to generate images. If you want to edit a photo, select the Edit Photo action from the menu.",
        "ERR_PHOTO_NO_MENU": "First, select the Edit Photo action in the bot menu, then send the image.",
        "ERR_UNSUPPORTED_MEDIA": "Sorry, I currently only support standard text descriptions, voice messages, and regular photos. Files, videos, and stickers are not supported."
    },
    "RU": {
        "BTN_GENERATE": "🎨 Сгенерировать фото",
        "BTN_EDIT": "🪄 Изменить фото",
        "BTN_HELP": "💡 Справка",
        "BTN_PRO": "💎 Детально (PRO)",
        "BTN_FLASH": "⚡️ Быстро (FLASH)",
        "BTN_LANG": "🌐 Language / Язык",
        "WELCOME": "Здравствуйте! 👋 Я бот, работающий на базе моделей Google Gemini.\n\nВыберите необходимое действие на клавиатуре ниже.",
        "CHOOSE_LANG": "Please select your language / Пожалуйста, выберите язык:",
        "LANG_SET": "Язык изменен на Русский 🇷🇺",
        "GENERATE_PROMPT": "✨ <b>Режим генерации активирован</b>\n\nПожалуйста, отправьте подробное описание (промпт) для изображения, которое вы ходите создать. Поддерживается текстовый и голосовой ввод.",
        "EDIT_PROMPT": "📸 Отправьте исходную <b>фотографию</b> в чат. После этого мы укажем, что именно нужно на ней изменить.",
        "HELP_TEXT": "💡 <b>Краткое руководство:</b>\n\n• <b>Сгенерировать фото</b>: Создание изображения с нуля на основе вашего описания.\n• <b>Изменить фото</b>: Редактирование существующей фотографии по дополнительной инструкции.\n• <b>Режимы качества (PRO/FLASH)</b>: FLASH подходит для быстрых скетчей и ответов, а PRO нужен для высококачественной проработки деталей.",
        "PRO_ACTIVATED": "💎 Включен режим PRO (Высокая детализация и качество).",
        "FLASH_ACTIVATED": "⚡️ Включен режим FLASH (Оптимизация и высокая скорость).",
        "ERR_SAFETY": "⚠️ Ошибка: Запрос отклонён фильтрами безопасности. Попробуйте изменить формулировку.",
        "ERR_RATELIMIT": "⏳ Превышен лимит запросов. Мы отправили слишком много команд. Пожалуйста, подождите минуту.",
        "ERR_SERVER": "🔌 Серверы Google Gemini временно недоступны. Пожалуйста, попробуйте запрос позже.",
        "ERR_UNKNOWN": "⚙️ Произошла неизвестная ошибка при обращении к API: {error}. Попробуйте ещё раз.",
        "ERR_GEN_INTERNAL": "😔 Произошел внутренний сбой сервиса генерации. Попробуйте снова чуть позже.",
        "ERR_EDIT_INTERNAL": "😔 Сервис редактирования недоступен. Попробуйте повторить операцию позднее.",
        "ERR_AUDIO_TRANS": "⚠️ Не удалось распознать голосовое сообщение. Пожалуйста, попробуйте написать текстом.",
        "PROCESS_GEN_START": "🎨 Процесс генерации запущен, ожидайте...",
        "ERR_LOAD_EDIT": "⚠️ Возникла проблема с загрузкой вашей фотографии. Выберите изменение фото в меню и попробуйте отправить еще раз.",
        "PROCESS_EDIT_PREP": "📥 Готовим вашу фотографию к преобразованиям...",
        "PROCESS_EDIT_GEN": "🪄 Генерируем изменения... Пожалуйста, подождите результат.",
        "ERR_DL_TELEGRAM": "😢 Ошибка при загрузке и обработке фотографии из Telegram. Пожалуйста, попробуйте повторить операцию.",
        "ERR_NEED_PHOTO_NOT_TEXT": "Пожалуйста, отправьте именно <b>фотографию</b> (изображение).",
        "ERR_MENU_FIRST": "Пожалуйста, сначала выберите нужное действие в меню бота (создать или изменить).",
        "VOICE_NO_PHOTO": "В рамках текущего действия ожидается <b>фотография</b>, а не голосовое сообщение.",
        "PROCESS_VOICE_RX": "🎧 Принимаю ваше аудиосообщение...",
        "PROCESS_VOICE_TRANS": "✍️ Перевожу голос в текст...",
        "TXT_TRANSCRIBED": "🎙 <i>Распознанный текст:</i> {text}",
        "ERR_VOICE_DL": "⚠️ Ошибка: не удалось загрузить аудиосообщение. Попробуйте записать и отправить повторно.",
        "PHOTO_LOADED_PROMPT": "📸 Фотография загружена. Напишите или отправьте голосом инструкцию: что нужно изменить на снимке?",
        "PHOTO_ALREADY_RX": "Фотография уже получена! Теперь просто отправьте текстовое или голосовое описание того, что нужно изменить.",
        "ERR_PHOTO_IN_GEN": "Данный режим работы поддерживает только текстовые запросы для создания изображений. Если вы хотите изменить фото, выберите действие изменения в меню.",
        "ERR_PHOTO_NO_MENU": "Сначала выберите кнопку изменения фото в меню бота, затем отправляйте изображение.",
        "ERR_UNSUPPORTED_MEDIA": "Извините, на данный момент я поддерживаю только текстовые описания, голосовые сообщения и обычные фотографии. Формат файлов, видео или стикеров не поддерживается."
    }
}
