from __future__ import annotations

from typing import Protocol

from banana_bot.domain import AudioResult, ImageResult, TextResult


class AIAdapter(Protocol):
    provider: str

    async def chat(self, model: str, messages: list[dict[str, str]], max_tokens: int) -> TextResult: ...
    async def image(self, model: str, prompt: str, options: dict[str, str]) -> ImageResult: ...
    async def edit_image(self, model: str, image: bytes, prompt: str, options: dict[str, str]) -> ImageResult: ...
    async def transcribe(self, model: str, audio: bytes) -> TextResult: ...
    async def analyze_file(self, model: str, content: bytes, mime_type: str, prompt: str, max_tokens: int) -> TextResult: ...
    async def synthesize(self, model: str, text: str, voice: str) -> AudioResult: ...
